logging:
  level:
    web: DEBUG
    org.springframework.data.r2dbc: DEBUG
spring:
  application.name: bootiful-web
  r2dbc:
    url: r2dbc:postgres://127.0.0.1:5432/coupons
    username: farmer
    password: q1w2e3..
  rabbitmq:
    host: 127.0.0.1
    username: guest
    password: q1w2e3..
  session:
    store-type: redis
  redis:
    host: 127.0.0.1

